#!/bin/bash

echo "🔧 GitHub Pages 快速修复脚本"
echo "=============================="

echo "📋 请按照以下步骤操作："
echo ""
echo "方案 1: 使用 GitHub Actions（推荐）"
echo "1. 进入您的 GitHub 仓库"
echo "2. 点击 Settings 标签页"
echo "3. 在左侧菜单中找到 Pages"
echo "4. 在 Source 部分选择 'GitHub Actions'"
echo "5. 点击 Save"
echo ""
echo "方案 2: 使用 gh-pages 分支"
echo "1. 进入您的 GitHub 仓库"
echo "2. 点击 Settings 标签页"
echo "3. 在左侧菜单中找到 Pages"
echo "4. 在 Source 部分选择 'Deploy from a branch'"
echo "5. 选择 'gh-pages' 分支（如果不存在，请先创建）"
echo "6. 选择 '/ (root)' 文件夹"
echo "7. 点击 Save"
echo ""
echo "8. 设置权限："
echo "   - Settings → Actions → General"
echo "   - Workflow permissions 选择 'Read and write permissions'"
echo ""
echo "9. 推送代码："
echo "   git add ."
echo "   git commit -m 'Fix GitHub Pages deployment'"
echo "   git push origin main"
echo ""
echo "10. 查看部署："
echo "    - 在 Actions 标签页查看部署进度"
echo "    - 访问 https://yourusername.github.io/actions-demo"
echo ""
echo "✅ 修复完成！"
echo ""
echo "如果仍然有问题，请查看 TROUBLESHOOTING.md 文件"